version: '3.8'
services:
  postgres:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviebot
    volumes:
      - postgres-movie-bot:/var/lib/postgresql/data
  movie-bot:
    depends_on:
      - postgres
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/moviebot
      BOT_TOKEN: ${BOT_TOKEN}
      API_KEY: ${API_KEY}
volumes:
  postgres-movie-bot: